#!/bin/bash
# filepath: /Users/chrisbrady/workspace/schematic/generate-schema-hash.sh

# Configuration
MODELS_DIR="$1"
OUTPUT_FILE="$2"

if [ -z "$MODELS_DIR" ] || [ -z "$OUTPUT_FILE" ]; then
    echo "Usage: $0 <models-directory> <output-file>"
    exit 1
fi

if [ ! -d "$MODELS_DIR" ]; then
    echo "Error: Models directory not found: $MODELS_DIR"
    exit 1
fi

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Find all .cs files in the models directory, sort them for consistency
FILES=$(find "$MODELS_DIR" -name "*.cs" | sort)

# Hash creation
echo "Hashing files in $MODELS_DIR..."

# Generate a combined hash of all model files
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS version using shasum
    HASH=$(cat $FILES | shasum -a 256 | cut -c1-8)
else
    # Linux version using sha256sum
    HASH=$(cat $FILES | sha256sum | cut -c1-8)
fi

# Generate the C# file
echo "Generating file: $OUTPUT_FILE with hash: $HASH"

cat > "$OUTPUT_FILE" << EOF
// Auto-generated code - do not modify
// This file is automatically generated based on model file changes

namespace Schematic.RulesEngine.Utils
{
    public static class GeneratedModelHash
    {
        /// <summary>
        /// Auto-generated hash of all model files.
        /// This value changes whenever any model file is modified.
        /// </summary>
        public const string Value = "$HASH";
    }
}
EOF

echo "Schema hash generation complete: $HASH"