// Auto-generated code - do not modify
// This file is automatically generated based on model file changes

namespace SchematicHQ.Client.RulesEngine.Utils
{
    public static class GeneratedModelHash
    {
        /// <summary>
        /// Auto-generated hash of all model files.
        /// This value changes whenever any model file is modified.
        /// </summary>
        public const string Value = "e024efa4";
    }
}
